# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_order_orderinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='oddnum',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='wuliu',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
