# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 06:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0005_auto_20180529_1303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'permissions': (('show_address', '查看地址管理'), ('insert_address', '添加地址管理'), ('edit_address', '修改地址管理'), ('del_address', '删除地址管理'))},
        ),
        migrations.AlterModelOptions(
            name='goods',
            options={'permissions': (('show_goods', '查看商品管理'), ('insert_goods', '添加商品管理'), ('edit_goods', '修改商品管理'), ('del_goods', '删除商品管理'))},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': (('show_order', '查看订单管理'), ('insert_order', '添加订单管理'), ('edit_order', '修改订单管理'), ('del_order', '删除订单管理'))},
        ),
        migrations.AlterModelOptions(
            name='types',
            options={'permissions': (('show_types', '查看商品分类管理'), ('insert_types', '添加商品分类管理'), ('edit_types', '修改商品分类管理'), ('del_types', '删除商品分类管理'))},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'permissions': (('show_users', '查看会员管理'), ('insert_users', '添加会员管理'), ('edit_users', '修改会员管理'), ('del_users', '删除会员管理'))},
        ),
    ]
